version: '3.8'

services:
  backend:
    build:
      context: .  # Path to Spring Boot app
      dockerfile: Dockerfile  # Ensure this is named Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/dev-dx-emp-list
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: 'postgres:latest'
    restart: always
    environment:
      POSTGRES_DB: dev-dx-emp-list
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: root
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
