spring:
  application:
    name: dx-emp-list-api
  datasource:
    url: jdbc:mysql://localhost:3306/dev-dx-emp-list
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        default_schema: public
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  servlet:
    context-path: /dx-emp-list-api
app:
  jwtExpirationMs: 86400000